### ISSUE TITLE
Some links to the documentation are broken

### ISSUE THREAD

**Issue by fratschi** [daveshanley/vacuum#116]
I would like to create a branch and fix this and create a PR but it seems to be that I haven't the rights to create a branch...

Here are the changes i made locally:

- [CLI Commands](https://quobix.com/vacuum/commands/)
  - [lint](https://quobix.com/vacuum/commands/lint/) 
  - [vacuum report](https://quobix.com/vacuum/commands/report/)
  - [dashboard](https://quobix.com/vacuum/commands/dashboard/)
  - [html-report](https://quobix.com/vacuum/commands/html-report/)
  - [spectral-report](https://quobix.com/vacuum/commands/spectral-report/)

**Comment by daveshanley** [comment]
Would you be able to fork the repo, make the fixes and push in a MR? That works well for most GitHub users.

**Comment by fratschi** [comment]
Of course! I created https://github.com/daveshanley/vacuum/pull/117

**Comment by daveshanley** [comment]
Thank you so much! approved and merged. Thanks for your help!
