### ISSUE TITLE
RFE: make `go install ./...` work

### ISSUE THREAD

**Issue by scop** [daveshanley/vacuum#135]
Currently:
```shellsession
$ go install ./...
# github.com/daveshanley/vacuum/plugin/sample
runtime.main_main·f: function main is undeclared in the main package
```

This isn't really a bug because it's not documented to work; instead there's a `Makefile` target for doing the intended thing, and plain `go install` does work.

Why I'm asking `go install ./...` to work is that I was preparing a [pre-commit](https://pre-commit.com) hook for inclusion here, and pre-commit [uses that command unconditionally](https://github.com/pre-commit/pre-commit/blob/028efcbd879ccdac7514ea4334462841bb0ca2c0/pre_commit/languages/golang.py#L83), so the installation will fail, and a native build of this tool in its current setup won't be auto-installable by pre-commit.

(pre-commit could install vacuum via the npm option I suppose, and at least with the docker image it would be usable, but those are not easily integratable in a config in this repo because both those options requires embedding the version in `.pre-commit-hooks.yaml` which to me looks like something that the maintainers here would have to remember to update manually before tagging new vacuum releases, or some automation added which would take care of that. The native install wouldn't have that problem.)

**Comment by daveshanley** [comment]
`go install ./...` now returns no errors, thank you for fixing this!
