### ISSUE TITLE
False unused/orphaned positive with polymorphic responses

### ISSUE THREAD

**Issue by scop** [daveshanley/vacuum#142]
```yaml
components:
  schemas:
    ErrSomething:
      # ...
paths:
  /fish/paste:
    get:
      responses:
        default:
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: "#/components/schemas/ErrSomething"
                  # ...
                discriminator:
                  # ...
```

Here, I get a warning
```
#/components/schemas/ErrSomething` is potentially unused or has been orphaned
```
This specific one seems to occur for polymorphic responses, i.e. components that are `schema` alternatives in a `oneOf` only in the doc, i.e. not as direct `$ref`s below response `schema`.

I haven't checked if this happens similarly for polymorphic requests, but I guess it might.

https://github.com/OAI/OpenAPI-Specification/blob/3.1.0/versions/3.1.0.md#discriminator-object

**Comment by daveshanley** [comment]
This was a bug, essentially two of the three `allOf`, `oneOf` and `anyOf` polymorphic collections available in the index, was not being checked as part of the `unused_definition` function. 

Thank you for your help in making vacuum better!
