### ISSUE TITLE
Path level parameters suppress warning on missing requestBody description

### ISSUE THREAD

**Issue by scop** [daveshanley/vacuum#148]
This structure correctly causes the warning
> Field `requestBody` for operation `post` at path `/some/path` is missing a description

```yaml
paths:
  /some/path:
    post:
      requestBody:
        # no description here
```

However, if the path has any path level parameters, the error is not emitted, for example:
```yaml
paths:
  /some/path/{id}:
    parameters:
      - in: path
        name: id
        type: string
    post:
      requestBody:
        # no description here, but no warning emitted
```

**Comment by daveshanley** [comment]
Nice catch! This should be fixed for sure. Working on it.

**Comment by daveshanley** [comment]
Fixed! Thank you for all your contributions and support.
