### ISSUE TITLE
The image with the `latest` tag is not the latest

### ISSUE THREAD

**Issue by schelv** [daveshanley/vacuum#153]
The image with the `latest` tag is not the latest.
See [here](https://hub.docker.com/r/dshanley/vacuum/tags?page=1&ordering=last_updated)

Maybe this can be automated?

**Comment by daveshanley** [comment]
oh, yes sorry I changed this around a while back, I don't tend to use the docker images, so it's not something I kept an eye on. I will tune up the pipeline to tag things correctly.

**Comment by daveshanley** [comment]
This has now been resolved, `latest` tag is correctly pushed with each build.

**Comment by schelv** [comment]
Could you also make the pipeline add tags for the releases?
