### ISSUE TITLE
Error for path ending with slash

### ISSUE THREAD

**Issue by scop** [daveshanley/vacuum#155]
Paths ending with slashes result in the error `Path must not end with a slash: matches the expression '.+\/$'`

The explanation at https://quobix.com/vacuum/rules/operations/path-keys-no-trailing-slash/ just says it's important not to do that, but provides no rationale. Spectral docs at https://meta.stoplight.io/docs/spectral/4dec24461f3af-open-api-rules#path-keys-no-trailing-slash do provide some reasoning, which makes sense to me.

However, I believe no OpenAPI specification actually forbids this. Therefore I was wondering if this should be downgraded to a warning, and perhaps the quobix.com/vacuum docs updated to elaborate a bit on the reasoning?

**Comment by daveshanley** [comment]
Docs have been updated, and the rule now throws a warning instead of an error

https://quobix.com/vacuum/rules/operations/path-keys-no-trailing-slash/

Thank you for helping make vacuum a better tool.
