### ISSUE TITLE
[req] site feature that can analyze pasted spec

### ISSUE THREAD

**Issue by spacether** [daveshanley/vacuum#162]
Can you please add a feature on your site that can analyze a pasted in spec?
Swagger editor has this and it is very helpful.
Thank you for making this tool!

**Comment by daveshanley** [comment]
This has been in my plan for some time, so yes - this will happen as soon as I have another feature I am working on completed.

Thank you!

**Comment by daveshanley** [comment]
This is now live at https://quobix.com/vacuum/demo/
