### ISSUE TITLE
Panic with incorrect info

### ISSUE THREAD

**Issue by hugoboos** [daveshanley/vacuum#163]
Linting the following file causes a panic:

```yaml
openapi: "3.1.0"
info: "test"
```

```
runtime error: index out of range [-1]
```

Caused by the `info-description` rule at https://github.com/daveshanley/vacuum/blob/main/functions/core/truthy.go#L57.

The `node.Content` being checked is empty.

Using the latest version with commit: `827bdef526f9afd954ffec54294753d1f29057a2`

**Comment by daveshanley** [comment]
Nice catch! I'll investigate and patch ASAP.

**Comment by daveshanley** [comment]
v0.0.36 has this issue resolved; thanks!
