### ISSUE TITLE
securitySchemas cause #/components/securitySchemes/APIKey is potentially unused or has been orphaned warning

### ISSUE THREAD

**Issue by TristanSpeakEasy** [daveshanley/vacuum#173]
Just sharing our OpenAPI doc that caused this: 

https://api.quobix.com/report?url=https://docs.speakeasyapi.dev/openapi.yaml

The #/components/securitySchemes/APIKey is technically referenced implicitly in the top level security object

```
security:
    - APIKey: []
```

https://swagger.io/docs/specification/authentication/

**Comment by daveshanley** [comment]
This has been resolved in v0.0.37

Thank you for helping make vacuum a better tool.
