### ISSUE TITLE
[req] vscode integration

### ISSUE THREAD

**Issue by TristanSpeakEasy** [daveshanley/vacuum#175]
would be great to see a vscode integration of this linter

**Comment by daveshanley** [comment]
Me too! I've yet to get much experience building VSCode integrations, however. I'd love this to be picked up by someone if they have time.

I won't be able to get to this for a while, January or February at the earliest.

**Comment by TristanSpeakEasy** [comment]
I might look at this myself, found this blog of someone documenting their journey implementing an openapi linter extension for vs code https://medium.com/ringcentral-developers/build-a-linter-extension-for-visual-studio-code-368a65a95545 looks like they potentially wrapped Spectral up for this so might be a drop in replacement in a fork of their repo

**Comment by daveshanley** [comment]
This is now in motion with #322

**Comment by daveshanley** [comment]
This is now available: 

https://quobix.com/vacuum/vscode/

https://marketplace.visualstudio.com/items?itemName=pb33f.vacuum
