### ISSUE TITLE
Spectral rule support

### ISSUE THREAD

**Issue by alexec** [daveshanley/vacuum#177]
Do you support all rules? Including rules in Javascript. Can you load the module from NPM?

**Comment by daveshanley** [comment]
Hi!

All the default rules created by spectral are supported; for more details, see here: https://quobix.com/vacuum/rules/

vacuum is not a JavaScript application. It's been written in pure Go, which means there is no JavaScript support for custom functions; however, custom functions are fully supported (you have to write them in go)

https://quobix.com/vacuum/api/custom-functions/

If you're looking for a pure JavaScript solution, I recommend sticking with Spectral, or using the redocly cli.
