### ISSUE TITLE
Disable rule by line

### ISSUE THREAD

**Issue by alexec** [daveshanley/vacuum#178]
Do you have the ability to disable a specific rule on a specific line of a specific spec?

Spectral does it like this:

`"x-spectral-lint-disable": "operation-default-response"`

https://github.com/stoplightio/spectral/issues/1558

**Comment by daveshanley** [comment]
Using extensions in the contract to target specifically isn't a great idea. If, at any point, someone wants to move to a new linter or a new set of tooling, the contract is littered with particular and (now useless) commands/comments that target individual tools. Which creates a huge mess over time.

Keeping the contract pure as a single source of truth is generally what I would recommend. Stuffing it full of tool-specific meta-data pollutes the contract for consumers who don't use that tooling (like clients)

This is the first time I've seen this use case come up. Generally, the desire to disable the linting of specific objects in an OpenAPI specification means the specification needs to be architected differently.

Turning off/disabling/customizing rules is 100% possible:  https://quobix.com/vacuum/rulesets/custom-rulesets/

But the rules are global, for now anyway - unless you'd like to take a stab at building the feature  :)

**Comment by alexec** [comment]
Thank you. That's really helpful.
