### ISSUE TITLE
Broken documentation link

### ISSUE THREAD

**Issue by harrtho** [daveshanley/vacuum#179]
The documentation at [oas3-schema](https://quobix.com/vacuum/rules/schemas/oas3-schema/) has a broken link to [Click to see schema](https://github.com/daveshanley/vacuum/blob/main/model/schemas/oas3-schema.yaml) -> (https://github.com/daveshanley/vacuum/blob/main/model/schemas/oas3-schema.yaml) instead of [Click to see schema](https://github.com/daveshanley/vacuum/blob/main/model/schemas/oas3-schema.json) -> (https://github.com/daveshanley/vacuum/blob/main/model/schemas/oas3-schema.json)

**Comment by daveshanley** [comment]
Thank you for finding this! I will fix it ASAP.

**Comment by daveshanley** [comment]
This has been resolved; thank you.
