### ISSUE TITLE
feature request: expose rule-id constants and a method for building rulesets programatically

### ISSUE THREAD

**Issue by TristanSpeakEasy** [daveshanley/vacuum#203]
Would love to be able to build a ruleset programmatically when using the API directly instead of via the CLI similar to how the default ruleset is built here: https://github.com/daveshanley/vacuum/blob/main/rulesets/rulesets.go#L251

Basically exposing the constants for the rule keys and maybe having a method that takes a map of rules and returns a ruleset that can be used in the ApplyRulesToRuleSet call

**Comment by daveshanley** [comment]
This is a good idea!

**Comment by daveshanley** [comment]
Now available in `v0.1.0` 

All the constants have been exposed and a couple of functions are available

- GetAllBuiltInRules()
- CreateRuleSetFromRuleMap()
