### ISSUE TITLE
feature request: rule to detect duplicate tag definitions

### ISSUE THREAD

**Issue by TristanSpeakEasy** [daveshanley/vacuum#206]
Along with checking if tags have descriptions would be good to have a rule to check for tag duplication. Ie two tags with the same name are defined in the global tag list

**Comment by daveshanley** [comment]
I guess I forgot that one, I thought I had it, but it's missing

https://quobix.com/vacuum/rules/tags/

I think this is a good rule to add.

**Comment by TristanSpeakEasy** [comment]
This is now handled by the oas3-schema rule
