### ISSUE TITLE
Stdin/stdout support

### ISSUE THREAD

**Issue by rliebz** [daveshanley/vacuum#220]
For integration with editors, accepting data from stdin and outputting to stdout is extremely helpful. 

Taking inputs from stdin means being able to give live updates when typing changes, without having to write the file to disk. Outputting machine parseable records to stdout (e.g., JSON or a one-line-per-message structured format) means being able to easily map results to editor-specific formats. While the built-in report formats are great (report, spectral-report), those force a write to disk rather than being available through stdout, and attempting workarounds such as `/dev/stdout` are difficult because of the pretty-printed info that's included in the normal output.

**Comment by daveshanley** [comment]
OK, sounds good!

**Comment by daveshanley** [comment]
This feature is now available in `v0.0.48`.

Both `report` and `spectral-report` support `stdin` and `stdout`. Using the `-i` (input) and `-o` flags (output). It's easy to pipe data in and pipe out without any disk IO.

The docs have been updated: 

- https://quobix.com/vacuum/commands/report/
- https://quobix.com/vacuum/commands/spectral-report/

A quick example:

```
cat "openapi: 3.0.1" | vacuum report -i -o | jq 
```
