### ISSUE TITLE
no-$ref-siblings URL Returns 404

### ISSUE THREAD

**Issue by saurami** [daveshanley/vacuum#222]
When violation "a `$ref` cannot be placed next to any other properties" is produced, the learn more about URL for [no-$ref-siblings](https://quobix.com/vacuum/rules/schemas/no-$ref-siblings) returns a 404

**Comment by daveshanley** [comment]
Will fix ASAP.

**Comment by daveshanley** [comment]
This has been fixed in `v0.0.48`
