### ISSUE TITLE
Junit reporting

### ISSUE THREAD

**Issue by 50rayn** [daveshanley/vacuum#233]
Hello.
I have a question regarding to reporting type. To be more exactly, I have a feature request. Is it possible to have reporting in junit format? Would be nice to have this feature, because I have a job in [Jenkins](https://plugins.jenkins.io/junit/) which I run it constantly and is required a JUnit reporting type. In the original [Spectral](https://github.com/stoplightio/spectral) has JUnit reporting, but they have an issue with blocks me using them.

Please, consider the [issue](https://github.com/stoplightio/spectral/issues/1555) addressed to the Spectral.

**Comment by daveshanley** [comment]
Cool idea! This will be useful.

**Comment by 50rayn** [comment]
Thanks @daveshanley . I'll wait this feature as soon as possible 💪.

**Comment by daveshanley** [comment]
I'm just finishing up some work on a new tool/docs, and then I will be heading back over here to do some feature work, this will be a part of it.

**Comment by 50rayn** [comment]
Hey. Looks like it works fine.
Thanks a lot @daveshanley 🤘🏻
