### ISSUE TITLE
Add support for multiple specifications.

### ISSUE THREAD

**Issue by daveshanley** [daveshanley/vacuum#249]
One spec is fun, but vacuum should be able to support multiple specifications, as many as you like.

- It should be able to find all the specifications through a directory recursively. 
- It should be able to resolve all exploded / remote specifications
- It should be able to accept a list of HTTP locations to download specifications from

**Comment by LasneF** [comment]
for info Spectral support the Glob syntax that is pretty nice 
https://github.com/mrmlnc/fast-glob#basic-syntax

**Comment by daveshanley** [comment]
in `v0.5.0` the lint command accepts multiple files or a glob pattern

For example: 

To lint multiple files, simply add them one after the other: 

`vacuum lint file1.yaml file2.json file3.yaml -d` 

To use a glob pattern:

`vacuum lint path/to/files/*.yaml` 

## Linting multiple files

![Screenshot 2023-11-17 at 6 11 36 PM](https://github.com/daveshanley/vacuum/assets/187345/883249f6-b0db-4b96-a87d-78f1e60c0a7f)

Multiple file support is only for the `lint` command at the moment, other commands require different treatment and cannot support multiple specs (like the `console` or the `html-report`) commands. An updated experience will be coming soon to support those commands.

## Resolving all remote and file based references. 

In `v0.4` of vacuum, a new component of `libopenapi` was introduced called 'the rolodex' which allows for correct anc accurate reference resolving and tracking across very large, exploded specifications.

A new flag was introduced `-r` / `--remote` to allow the automatic lookup of these references. 

in `v0.5.0` this flag has been permanently set to 'true' for the `lint` command. There is no need to specify it, it's hard wired to on and cannot be turned off. This is the expected behavior for all use-cases, so it's been turned on permanently.
