### ISSUE TITLE
Custom ruleset for verifying referenced resources

### ISSUE THREAD

**Issue by LittleGreenYoda42** [daveshanley/vacuum#257]
Defined custom rules don't seem to follow referenced resources within the document.

In the documentation there is a paragraph about [resolved documents](https://quobix.com/vacuum/rulesets/custom-rulesets/#resolved). The default behavior is described to be working on the resolved document.

Nevertheless the following example just shows an error for the schema definition in place and not for the referenced one.
Is this a bug or expected behavior?

example openAPI file:
```
openapi: 3.0.0
info:
  title: Minimal example
  version: 1.0.0
paths:
  /:
    get:
      responses:
        "200":
          description: "Test"
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: "#/components/schemas/Response"
        "404":
          description: "Test not found"
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "500":
          content:
            application/json;charset=UTF-8:
              schema:
                type: object
                properties:
                  error:
                    type: string
components:
  schemas:
    Response:
      type: object
      properties:
        id:
          type: string
    ErrorResponse:
      type: object
      properties:
        error:
          type: string
```

custom ruleset:
```
description: Ruleset following refs.
extends: [[spectral:oas, off]]
rules:
  response-contains-id:
    description: "The response is supposed to contain an id."
    type: validation
    given: $.paths.*.*.responses.*.content.*.schema.properties
    howToFix: Each response is supposed to contain an id.
    severity: error
    then:
      field: id
      function: truthy
```

**Comment by daveshanley** [comment]
Oh, interesting! This may be a really easy fix, there are two versions of the model in memory, one is resolved one is unresolved and custom rules may be using the wrong one.  I will look into this for you during the next bug sweep!

**Comment by daveshanley** [comment]
I normally run a bug sweep every few weeks, depending on how heavy the stack is. At the moment this is the only reported bug, so i'll most likely be able to swing back around before the end of this month.

**Comment by LittleGreenYoda42** [comment]
That sounds great. Thanks again. In the meantime we can just add `resolved: true` to the rules which seems to be a workaround for now.

**Comment by daveshanley** [comment]
Please try `v0.1.0` and let me know how you get on.
