### ISSUE TITLE
bug: examples for array properties are not recognized correctly

### ISSUE THREAD

**Issue by bravenut** [daveshanley/vacuum#258]
Hi,
First of all, I very much enjoy using your tool, the API is pretty fast and straightforward to use. Yesterday, I stumpled upon what I assume to be a bug when trying to make my OAS clean and compliant to OAS 3 standards (it may be related to [this issue](https://github.com/daveshanley/vacuum/issues/229)). My ruleset is extending the spectral:oas default rules and is not overwriting anything. I'm trying to achieve zero warnings for the following example OAS:

```
openapi: 3.0.3
info:
  title: Example API
  description: Example Description
  version: "1.0"
servers:
  - url: https://localhost:8090
    description: someserver
paths:
  /v1/chickens:
    get:
      summary: Get all the chickens
      description: Get chickens
      operationId: Service_GetChickens
      tags:
        - Chicken
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SomeEndpointResponse'
components:
  schemas:
    SomeEndpointResponse:
      title: Endpoint response
      type: object
      properties:
        someProperty:
          example: "5"
          type: string
          description: Simple string property
        someArrayProperty:
          type: array
          items:
            type: string
          description: Array property
          example:
            - abc
            - def
tags:
  - name: Chicken
```

Vacuum does a good job checking for everything in my OAS besides one last (false-positive) warning on the oas3-valid-schema-example rule:
```
{
        "code": "oas3-valid-schema-example",
        "path": [
            "components",
            "schemas",
            "SomeEndpointResponse",
            "someArrayProperty"
        ],
        "message": "Example for property `someArrayProperty` is not valid: `Invalid type. Expected: string, given: array`. Value `[abc def]` is not compatible",
        "severity": 1,
        "range": {
            "start": {
                "line": 39,
                "character": 11
            },
            "end": {
                "line": 40,
                "character": 13
            }
        },
        "source": "example.yaml"
}
```

It's expecting an example of type string for a property which is an array of strings. I would assume no warning to be thrown here (I get none on spectral). Would be nice if you could have a look into it, I would really appreciate it!
Cheers Max

**Comment by daveshanley** [comment]
Please try `v0.1.0` and let me know how you get on.

**Comment by daveshanley** [comment]
I re-ran your sample spec, it now scores perfectly. Your run towards a perfect contract is that much closer.
