### ISSUE TITLE
bug: Not uniform responses from violated custom rules using core functions

### ISSUE THREAD

**Issue by LittleGreenYoda42** [daveshanley/vacuum#260]
After defining some custom rules we noticed that the output message format for the different core functions is not the same. 
Some core functions (e.g. truthy) will return the rule description and add a part with details. Other functions (e.g. undefined or casing) will not show the rule description but only the value and what's wrong with it. 

It would be great to have the description followed by the details as it is for truthy.

Hint: When checking the vacuum implementation I found the `if context.Rule.Description != ""` for undefined and casing while this check is not done for truthy. It seams `that context.Rule.Description` is evaluated as empty even if it was set in the rule.

**Comment by daveshanley** [comment]
I think this is down to me rushing about a year ago. I'll look into this as a part of the next bug sweep happening soon.

**Comment by daveshanley** [comment]
This has been resolved in `v0.1.0`. All core functions follow the same pattern for output.

**Comment by LittleGreenYoda42** [comment]
Thanks @daveshanley
