### ISSUE TITLE
Vacuum does not return error if there is an error on reference

### ISSUE THREAD

**Issue by sezgigumus** [daveshanley/vacuum#261]
Vacuum does not return an error if there is an error on the reference definitions.
Please see the examples below:

**routes.yaml:**
```
openapi: 3.0.0
info:
  title: Test APIs
  description: Documentation for Test APIs
  version: '1.0'
  contact:
    name: Test team
    x-slack-channel: '#test-team'
servers: 
  - url: 'http://localhost:8080'
    description: Local server 
tags: 
  - name: projects
    description: Projects 
paths:
  /api/test/v1/projects/{projectId}:
    $ref: get.yaml
```

**get.yaml:**
```
get:
  summary: 'Get projects'
  description: 'There is a test'
  tags: 
    -  projects
  parameters: 
    - $ref: '../base/component-base.yaml#/components/parameters/projectId'
  responses:
    "200":
      description: OK
      content:
        application/json:
          schema:
            $ref: '../base/component-base.yaml#/components/schemas/ProjectResponse'
    '400':
      description: 'fail'
```

Output:
```
          Linting passed, A perfect score! well done!          
```

However, when the reference is removed and the `get` path is defined in the same file, Vacuum returns an error for missing `operationId`.

**single routes.yaml:**
```
openapi: 3.0.0
info:
  title: Test APIs
  description: Documentation for Test APIs
  version: '1.0'
  contact:
    name: Test team
    x-slack-channel: '#test-team'
servers: 
  - url: 'http://localhost:8080'
    description: Local server 
tags: 
  - name: projects
    description: Projects 
paths:
  /api/test/v1/projects/{projectId}:
    get:
      summary: 'Get projects'
      description: 'There is test'
      tags: 
        -  projects
      parameters: 
        - $ref: '../base/component-base.yaml#/components/parameters/projectId'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '../base/component-base.yaml#/components/schemas/ProjectResponse'
        '400':
          description: 'fail'
```

Output:
```
# Operations Issues

Line / Column | Severity | Message                                                                                         | Path                                         
(18:7)        | error    | the 'get' operation at path '/api/test/v1/projects/{projectId}' does not contain an operationId | $.paths./api/test/v1/projects/{projectId}.get

Category   | Errors | Warnings | Info
Operations | 1      | 0        | 0   
```

I am wondering if this is a bug or missing feature. If it is a missing feature, do you have plans to implement it?
Also, I am interested in one of the open issue https://github.com/daveshanley/vacuum/issues/230 Could you please tell me its status update?
Thanks

**Comment by daveshanley** [comment]
This is a missing feature rather than a bug, it's the same problem as #230 vacuum needs more intelligence to detect this.

**Comment by daveshanley** [comment]
Please try `v0.1.0` and let me know how you get on.

**Comment by sezgigumus** [comment]
Hi @daveshanley thanks for quick fix

Now, I get a `circular-references` error after using `0.1.0` version. Please see the example:

Command: `vacuum report v1/routes.yaml -p v1`

`v1/routes.yaml`
```
components:
  schema:
    testSchema:
      type: object
      metadata:
        $ref: >-
          ../base-yaml#/components/schemas/metadata
```

`base.yaml`
```
components:
  schema:
    metadata:
      type: object
      properties:
        data1:
          type: string
          description: data 1
        data2:
          type: string
          description: data 2
```

The error that I get:
```
  {
      "message": "cannot resolve reference `../base.yaml#/components/schemas/metadata`, it's missing: $components.schemas['metadata'] [...:..]",
      "range": {
          ...
      },
      "path": "$components.schemas['metadata']",
      "ruleId": "circular-references",
      "ruleSeverity": "error"
  }
```

Could you please tell me if there is any problem on my side or if it is a bug in this version? Thanks

**Comment by daveshanley** [comment]
Hi @sezgigumus 

What you're now seeing is improved detection for missing references or un-resolved references. This is supposed to happen, before these bad refs were not being reported. 

However what is wrong here, is that the rule is marked as 'circular-references' it should not be lumped into that category. I will fix that to be something appropriate, however the error is accurate. 


To use local / remote or relative references, use the `-p` / `--base` flag to set a base director or URL for vacuum to use to look up the references.

https://quobix.com/vacuum/commands/lint/

Thanks

**Comment by daveshanley** [comment]
I cleaned up the rule for reporting circular references and resolving issues in `v0.1.1`
