### ISSUE TITLE
Error in version 0.1.0

### ISSUE THREAD

**Issue by bebez024** [daveshanley/vacuum#266]
Hey @daveshanley,

we experienced this problem in the version 0.1.0 (the same open api specification worked fine in version 0.0.55)

`panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x76c7a6]
goroutine 5395 [running]:
github.com/pb33f/libopenapi/utils.IsNodeRefValue(...)
	/home/runner/go/pkg/mod/github.com/pb33f/libopenapi@v0.8.1/utils/utils.go:420
github.com/pb33f/libopenapi/datamodel/low/base.(*Schema).Build(0xc003c37800, 0x0, 0xc0001eaa00)
	/home/runner/go/pkg/mod/github.com/pb33f/libopenapi@v0.8.1/datamodel/low/base/schema.go:524 +0x86
github.com/daveshanley/vacuum/parser.ConvertNodeIntoJSONSchema(0xdf7682?, 0xd?)
	/home/runner/work/vacuum/vacuum/parser/json_schema.go:149 +0x65
github.com/daveshanley/vacuum/functions/openapi.analyzeExample({0xc0004339e0, 0xa}, 0xc000706640, {0xc0013b1780, 0x33}, 0xc001cf5d58?, {0xc002c61080, 0xc000427c30, {0xccc080, 0xc0002b7cc0}, ...})
	/home/runner/work/vacuum/vacuum/functions/openapi/examples.go:[48](https://gitlabci.exxeta.com/eXXatt/exxatt-core-service/-/jobs/779010#L48)4 +0x11a6
github.com/daveshanley/vacuum/functions/openapi.checkExamples(0xc000706280, {0xc0013b1780, 0x33}, 0xc001a15e00?, {0xc002c61080, 0xc000427c30, {0xccc080, 0xc0002b7cc0}, {0x0, 0x0}, ...})
	/home/runner/work/vacuum/vacuum/functions/openapi/examples.go:416 +0x1b2
github.com/daveshanley/vacuum/functions/openapi.checkExampleAsync(0xc001c99560?, 0x10e?, {0xc0013b1780?, 0x1[51](https://gitlabci.exxeta.com/eXXatt/exxatt-core-service/-/jobs/779010#L51)?}, 0x0?, {0xc002c61080, 0xc000427c30, {0xccc080, 0xc0002b7cc0}, {0x0, ...}, ...})
	/home/runner/work/vacuum/vacuum/functions/openapi/examples.go:32 +0x65
created by github.com/daveshanley/vacuum/functions/openapi.Examples.RunRule
	/home/runner/work/vacuum/vacuum/functions/openapi/examples.go:142 +0x185`

**Comment by daveshanley** [comment]
Will investigate ASAP.

**Comment by daveshanley** [comment]
Can you provide the specification that is triggering this issue? It's a lower level issue than vacuum and I cannot fire the result using the test suite.

**Comment by greg-signi** [comment]
Hello, we can also confirm we had this issue. Just downgraded to another version `:main`. I did not see tag `0.0.55` in the registry
https://hub.docker.com/r/dshanley/vacuum/tags

**Comment by daveshanley** [comment]
> Hello, we can also confirm we had this issue. Just downgraded to another version `main`. I did not see tag `0.0.55` in the registry https://hub.docker.com/r/dshanley/vacuum/tags

I don't think I set things up to publish a tag, just latest for docker. 

If someone sends me a spec that triggers this error, I will diagnose the problem and have a fix out pretty fast.

**Comment by bebez024** [comment]
@daveshanley you can find the specs here: http://api-doc.exxeta.auction.s3.eu-central-1.amazonaws.com/api/2023.2.0-RC1.json

**Comment by daveshanley** [comment]
Thanks for the spec, I found the issue, a small oversight and has been addressed in `v0.1.1` 

Let me know how you get on.

**Comment by bebez024** [comment]
@daveshanley works great, thank you :) 

note: there are also vulnerabilities since version 0.1.0
![image](https://user-images.githubusercontent.com/9437827/236388846-f0796db5-3f78-49e3-b2e4-0f50000c7374.png)
