### ISSUE TITLE
Display warnings

### ISSUE THREAD

**Issue by nmoreaud** [daveshanley/vacuum#278]
Hello,
How can I make `vacuum lint` show warnings?

**Comment by nmoreaud** [comment]
Ok, in fact -d displays warnings, and -x hides them (and the logo).
It would be nice to be able to toggle each section visibility separately (logo, list of errors, summary table, summary message)

**Comment by daveshanley** [comment]
In `v0.6.0` New flags were added to enable this. 

https://quobix.com/vacuum/commands/lint/#available-flags

`-m` turns off the summary message
`-b` turns off the banner
