### ISSUE TITLE
Server URL: Can be relative to OpenAPI Document ("/" is valid?)

### ISSUE THREAD

**Issue by pquerna** [daveshanley/vacuum#284]
The server object, can allow a path like "/" -- "relative" to the OAS file:

https://spec.openapis.org/oas/v3.1.0#server-object

```
servers:
  - description: The server for bookstore.v1.BookstoreService.
    url: /
```

But `vacuum` currently will treat this as an error:
```
# Validation Issues

Line / Column | Severity | Message                                                 | Path
(326:5)       | error    | Server URL is not valid: must not have a trailing slash | $.servers[0].url

```

I get that ... it might not be right in many cases, could easily see it being an Info/warning?

**Comment by daveshanley** [comment]
I think a warning makes sense here; technically, it's not incorrect. It's just not very useful - and should not error out by default.

**Comment by daveshanley** [comment]
This was changed to a warning in `v0.6.0`
