### ISSUE TITLE
install.sh: avoid intermittent installation failures due to transient errors from GitHub

### ISSUE THREAD

**Issue by markdespain** [daveshanley/vacuum#291]
As part of building some Docker containers, I encountered sporadic installation failures with the following error.
```
 > [12/18] RUN curl -fsSL https://quobix.com/scripts/install_vacuum.sh | sh:
#16 0.487 Downloading https://github.com/daveshanley/vacuum/releases/download/vlinux/vacuum_linux_x86_64_.tar.gz
#16 0.751 https://github.com/daveshanley/vacuum/releases/download/v/checksums.txt
#16 0.994 Error: Checksums do not match
```

My colleague noted that the version number in the URL is missing.  Together, we came to arrived at the belief that this was due to an intermittent failure returned by GitHub within the get_latest_release function (relevant code below).
```
# get_latest_release "daveshanley/vacuum"
get_latest_release() {
  curl --silent "https://api.github.com/repos/$1/releases/latest" | # Get latest release from GitHub api
    grep '"tag_name":' |                                            # Get tag line
    sed -E 's/.*"([^"]+)".*/\1/'                                    # Pluck JSON value
}
```

Additionally, he ran a few times locally and was able to produce this error response from GitHub (which I would presume was not a 200 response).
```
{"message":"API rate limit exceeded for 103.175.111.222. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)","documentation_url":"https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting"}
```

An easy improvement might be to update the curl call to make use of retries, like described at https://everything.curl.dev/usingcurl/downloads/retry

**Comment by daveshanley** [comment]
Yeah that rate limit issue is a real pain, I think it's 50 requests an hour when unauthenticated. 

Thank you for the tip! This has been updated on quobix.com and the source will be updated here with the next release.

**Comment by markdespain** [comment]
Excellent, thank you!
