### ISSUE TITLE
Show all violations when --all flag passed

### ISSUE THREAD

**Issue by roessland** [daveshanley/vacuum#293]
My spec has a bit too many warnings right now, causing useful warnings to be omitted in the report.

```
...123 more violations not rendered.
```

Summary:
```
Category     | Errors | Warnings | Info
Operations   | 0      | 2        | 0
Descriptions | 0      | 97       | 168
Examples     | 0      | 166      | 0
```

It would be nice to have a flag for returning _all_ violations and not omit any.

I'm happy to contribute if you would accept a PR for this.

**Comment by daveshanley** [comment]
If you would like to submit a PR, submissions are welcome!

**Comment by daveshanley** [comment]
This was added in `v0.6.0`

The `-a` / `--all-results` will print out all results, regardless of number when using `-d`

Docs: https://quobix.com/vacuum/commands/lint/#available-flags
