### ISSUE TITLE
Language Server Protocol

### ISSUE THREAD

**Issue by KDanisme** [daveshanley/vacuum#298]
I just stumbled on this project and i find it great.
It would be cool if i could get completion/warning/errors in my IDE of choice.
How can i go about implementing an LSP for this? seems like a fun project
Its sort of a duplicate of #175 but an Lsp could be used everywhere that supports it

**Comment by daveshanley** [comment]
That would be awesome!

**Comment by kevinduffey** [comment]
Yes please! LSP Would be a fantastic add.

**Comment by daveshanley** [comment]
Language server was added in `v0.9`
 
[docs can be found here](https://quobix.com/vacuum/commands/language-server/)
