### ISSUE TITLE
ApplyRulesToRuleSet ignores RuleSetExecution.Document when provided 

### ISSUE THREAD

**Issue by FedeBev** [daveshanley/vacuum#299]
Hi there,

I noticed that when a document is provided directly, nothing happens

```go
lintingResults := motor.ApplyRulesToRuleSet(
&motor.RuleSetExecution{
	RuleSet: recommendedRS,
	Document: document,
})
```

I suppose that when a document is provided, [these lines](https://github.com/daveshanley/vacuum/blob/67d40ab576f7e23a1bc4aecaade09ec988644d30/motor/rule_applicator.go#L81-L153) should be skipped.

I can take care of  the fix if you agree with my supposition.

Thanks

**Comment by daveshanley** [comment]
Yes, this should be the correct behavior.
