### ISSUE TITLE
Indention error cannot detect

### ISSUE THREAD

**Issue by vient28** [daveshanley/vacuum#301]
My open-api.yml have idention error but it cannot detect it
```
paths:
     /test
```

It should be

```
paths:
  /test
```
Its saying no error

Anyone can check?

**Comment by daveshanley** [comment]
YAML is white space delimited. As long as all the spaces are consistent, it does not matter how many spaces you use as white space. 

This is not a YAML linter. It's an OpenAPI linter, if you get no error - then the library can read the spec.
