### ISSUE TITLE
Incorrect path reported using `oas3-valid-schema-example`

### ISSUE THREAD

**Issue by AdrianMachado** [daveshanley/vacuum#304]
## Description

When running Vacuum against [Asan's Open API](https://api.apis.guru/v2/specs/asana.com/1.0/openapi.json) I encountered a strange path for the `oas3-valid-schema-example` rule. 

```js
{
  code: 'oas3-valid-schema-example',
  path: [ 'parameters', 'parameters[5]' ],
  message: 'Schema for `actor_gid` does not contain any examples or example data',
  severity: 1,
  range: {
    start: { line: 10948, character: 9 },
    end: { line: 10948, character: 19 }
  },
  source: 'example-specs/asana.json'
}
```

## Expected Output

I would expect the path should instead be `['paths', '/workspaces/{workspace_gid}/audit_log_events'. 'parameters', 'parameters[5]']`
Perhaps this is some weird edge case when params are defined on the path instead of on the operation?

**Comment by daveshanley** [comment]
This has been fixed in `v0.7.0`
