### ISSUE TITLE
vacuum lint --base . is not working as expected

### ISSUE THREAD

**Issue by jasonquigleyhpecom** [daveshanley/vacuum#319]
Hello Dave,

I am running `vacuum lint --base .` against this file and it says that the schema is invalid:

```
openapi: 3.1.0
info:
  title: Burgers
  license:
    name: License Agreement
    url: https://www.example.com/licensing.html
  version: latest
  description: |
    More burgers!
    A unified API for consuming burgers 
  contact:
    name: Ronald Macdonald
    email: burgers@example.com

servers:
  - url: https://api.example.com
    description: Development environment

externalDocs:
  description: Find out more about burgers
  url: https://www.example.com

security:
  - Bearer: []

paths:
  /burgers/create-burger:
    $ref: "./burgers-ref.yaml"

components:
  securitySchemes:
    Bearer:
      description: Uses a token for authorization
      type: http
      scheme: bearer
```

This was mentioned in #314 so I assume it was working then.

I'm running the latest code from the `main` branch.

**Comment by daveshanley** [comment]
I'll have a look for you asap.

**Comment by daveshanley** [comment]
Hi, this is all working as expected. I just tried this exact example locally, and I also got a warning about the schema. The file is located and pulled in just fine (otherwise, you would get an error about vacuum not finding the file and file lookups need to be enabled).

The schema error is real. You cannot use a `$ref` for a path definition. 

https://spec.openapis.org/oas/latest.html#paths-object

It's not valid OpenAPI.

**Comment by jasonquigleyhpecom** [comment]
Thank you @daveshanley ! I guess I'll have to re-read the specs with a lot more coffee this time!

**Comment by jasonquigleyhpecom** [comment]
Hi Dave, would this [Reference Object](https://spec.openapis.org/oas/latest.html#referenceObject) have any impact on your thinking?

**Comment by daveshanley** [comment]
Hi Jason, Yeah references are fine, except there are some places you cannot use them, not legally anyway. Most tooling will adapt around them (including mine), however if you want a valid OpenAPI spec, you can't use a $ref for a path definition. Tools will work (or should do), but it's not technically legal.

**Comment by jasonquigleyhpecom** [comment]
Okay, thanks Dave!
