### ISSUE TITLE
Cli usage is misleading

### ISSUE THREAD

**Issue by KDanisme** [daveshanley/vacuum#323]
Vacuum commands which accept a file parameter have a misleading help page.
Usage shows: ` vacuum lint [flags]`
which is missing a file argument.

Whilst the `vacuum --help` command shows: `vacuum lint <your-openapi-file.yaml> [flags]`
Which is more correct.

**Comment by daveshanley** [comment]
Thank you for reporting this, I will look to clean it up as soon as possible.

**Comment by daveshanley** [comment]
fixed in `v0.3.3`
