### ISSUE TITLE
Vacuum custom functions fail to run

### ISSUE THREAD

**Issue by aabedraba** [daveshanley/vacuum#331]
I'm trying to run the sample in the repo following these commands from the root of the project: 

```
cd plugin/sample
go mod init sample
go mod tidy 
cd ../.. # back to root
vacuum lint -r rulesets/examples/sample-plugin-ruleset.yaml -f ./plugin/sample ~/path/to/openapi
```

And I get this output: 

```sh
INFO  Located custom function plugin: boot.so
ERROR   Unable to open custom functions: plugin: not implemented
```

## Debug details 

Go version: tried 18, 19, 20, 21
Machine: tried Mac M2 ARM and Ubuntu 20.4 x86

**Comment by daveshanley** [comment]
This is strange, I am going to look into this.

**Comment by daveshanley** [comment]
`fatal error: forcegc: phase error` <-- I can't help with this. It's for sure an SDK issue with golang on the OS. 

Also, you will need to recompile vacuum if the version of go you're using is different from the one vacuum was compiled against.

Currently, vacuum is compiled against version `go version go1.21.0 linux/amd64`

**Comment by aabedraba** [comment]
Thanks a ton :)
