### ISSUE TITLE
Add support for machine-only/compressed version of JUnit report format

### ISSUE THREAD

**Issue by fkleon** [daveshanley/vacuum#354]
The output of `report --junit $SPEC` is always pretty-printed, even if `--no-pretty` is given.

**Comment by daveshanley** [comment]
OK, will fix on next bug run.

**Comment by fkleon** [comment]
It's just a very minor issue, these files aren't very big to start with, so no major savings to gain.

After thinking about it further, I'm also not sure that the multi-line descriptions would come through nicely (probably would need newline escaping or a `CDATA` block).

Might not be worth the effort after all!

**Comment by daveshanley** [comment]
Should we close this then?

**Comment by fkleon** [comment]
Yep, happy to close.
