### ISSUE TITLE
Broken 'Learn more about' link in HTML report

### ISSUE THREAD

**Issue by ikenna** [daveshanley/vacuum#355]
The 'Learn more about' link in the HTML report provides a link that appears to be broken due to a casing issue. 
For example, the link in the below links to https://quobix.com/vacuum/rules/OWASP/owasp-integer-format/ which returns a 404.  I think the URL that actually works is https://quobix.com/vacuum/rules/owasp/owasp-integer-format/ .

![Vacuum-issue](https://github.com/daveshanley/vacuum/assets/1222298/6b6aa9ed-27b5-45cc-b98a-02d949fcaa3a)

**Comment by daveshanley** [comment]
This has been resolved in `v0.4.0` and up.
