### ISSUE TITLE
--fail-severity warn always says "Linting passed"

### ISSUE THREAD

**Issue by ajoga** [daveshanley/vacuum#361]
Hello,

Running `docker run --rm -v $PWD:/work:ro dshanley/vacuum:v0.4.3 lint specs/mrc.yml  --fail-severity warn` on an `mrc.yml` file that yields a warn gives a "Linting passed" message that is misleading.

Oddly enough, the return code is correctly `1` in these circumstances, and is correctly `0` if I do not specify `--fail-severity`.

`mrc.yml`:

```
openapi: 3.0.0
info:
  title: aaaa
  description: aaa
  version: 1.0.0
servers:
  - url: /test
tags:
  - name: Account
paths:
  /accounts:
    get:
      operationId: gfdgfd
      tags:
        - Account
      description: dfdfsds
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: string

```

**Comment by daveshanley** [comment]
This has been fixed in `v0.5.0`

![Screenshot 2023-11-18 at 9 23 31 AM](https://github.com/daveshanley/vacuum/assets/187345/1ced78c9-248b-43e9-a166-f064a49e831e)
