### ISSUE TITLE
Feature Request : Capacity to bundle spec into a single one

### ISSUE THREAD

**Issue by LasneF** [daveshanley/vacuum#368]
given an OAS spec spread in multiple files (leveraging $ref: ./paths/xxx.yml for instance

capacity to bundle all those file into a standalone, self sufficent file 

proposed syntax : vacuum bundle split.yml -o target.yml 

may be not sure usefull could be otherwise an option like
vacuum lint split.yml -bundle target.yml 

similar functionnality exists in redocly-cli  (https://redocly.com/docs/cli/commands/bundle/ ) 

NB : 
as a classical pb ,  in some circunstances you might need to generate adhoc naming as sometime it conflics

also an option like merging 2 existing apispec could be usefull as well 
use case beeing to have a 360 view of several api spec in a unified one

**Comment by daveshanley** [comment]
This has been added in `v0.8.0` via the new `bundle` command

Docs: https://quobix.com/vacuum/commands/bundle/
