### ISSUE TITLE
Online Version : OWASP check or not Display

### ISSUE THREAD

**Issue by LasneF** [daveshanley/vacuum#399]
Given the online sample , OWASP validation is not checked 

but it is displayed as no error 
![image](https://github.com/daveshanley/vacuum/assets/12461661/6ca97d11-b4ec-41d1-ae83-77162ee1766c)

1) if a rulesset is not enabled it should not be part of the reports otherwise it creates kind of lying experience 

1) Online version should have a tick to check owasp or not (and if so should not display it as part of the report)

**Comment by daveshanley** [comment]
Yes this is a good idea. Will add.

**Comment by LasneF** [comment]
the online part has been implemented (point 2) 

the (1) if if ruleset is not , we may close or not this ticket

**Comment by daveshanley** [comment]
I still need to adjust the html-report and the terminal UI to not show the OWASP categories, (or show a not enabled message). So let's keep this open until the job is fully done.

**Comment by daveshanley** [comment]
in `v0.7.0` the categories that have no results are hidden from the HTML report and the dashboard (tui). 

This is now complete.
