### ISSUE TITLE
Failure to find Globbed files when trying to run the linter as part of Github Actions

### ISSUE THREAD

**Issue by volovikariel** [daveshanley/vacuum#406]
In [my repo](https://github.com/volovikariel/IdentityManager/tree/2a2ec4dba4972d88f77043d3edefa617fdf8ed4a), the
lint stage of my GHWF [failed](https://github.com/volovikariel/IdentityManager/actions/runs/7388492359/job/20099442181) with `INFO  Linting file './internal/docs/apis/**/*.yaml' against 42 rules: https://quobix.com/vacuum/rulesets/recommended`, despite running fine locally
![image](https://github.com/daveshanley/vacuum/assets/16262535/261e303c-aca5-403f-928c-80a45b0c1978)

Running it with a `find` command instead [works fine](https://github.com/volovikariel/IdentityManager/actions/runs/7389305879/job/20101851361).

Any idea why Globs don't seem to work in GH Actions?

**Comment by daveshanley** [comment]
My guess is that its the shell which is doing the globbing, vacuum is getting pre-globbed files most of the time directly from the shell. 

The same problem exists on windows, so this is a feature we need to add.

**Comment by volovikariel** [comment]
I see. I'm not sure what the standard way of going about this is, as a file name *could* contain `*` characters.
![image](https://github.com/daveshanley/vacuum/assets/16262535/d98e9dc6-ffb1-4d66-b38e-f45fb58a0e50)

Should the user pass in a flag to signify that it's a Glob pattern, and then we can simply(?) use `filepath::glob` to generate a slice of file names as opposed to relying on `args` [here](https://github.com/daveshanley/vacuum/blob/40f34845d3f2daeb75ac8a9dc7dffffbc5e12dfd/cmd/lint.go#L128C16-L128C16)?

**Comment by daveshanley** [comment]
I think we will need to, there isn't any other way to determine a pattern is being used, if the shell is not globbing for us.
