### ISSUE TITLE
JSON Path support improvements needed

### ISSUE THREAD

**Issue by AdrianMachado** [daveshanley/vacuum#419]
## Summary

I am testing our custom javascript functions right now - it seems like they aren't triggering `given` the way I would expect. 

I think that if the `given` contains [\*] - it will not work
Ex. $.paths..requestBody.content works
$.paths[\*].[\*].requestBody.content does not

Both produce the same result on https://jsonpath.com/ FWIW

**Comment by daveshanley** [comment]
Unfortunatley, I don't have control over this part of the application stack, it's provided by a library called `yaml-jsonpath` (https://github.com/vmware-labs/yaml-jsonpath). 

There are no plans to rewrite it, and there is no alternative that I know of.

The supported syntax is documented in the readme of the repo:

**Comment by AdrianMachado** [comment]
Looks like there's an RFC for JSON path now - hopefully the underlying lib gets updated soon
