### ISSUE TITLE
$ref looks not supported on path 

### ISSUE THREAD

**Issue by LasneF** [daveshanley/vacuum#422]
given the  pattern below 

paths:
  /orders:
    $ref: paths/orders.yaml
    
it looks not supported as giving me the below error
\openapi.yaml:33:11 | error    | schema invalid: not allowed                                                                        | oas3-schema          | Schemas    | $.paths['/orders'].$ref
.\openapi.yaml:35:11 | error    | schema invalid: not allowed                                                                        | oas3-schema          | Schemas    | $.paths['/orders/{order-id}'].$ref      

BUT this pattern is valid according to OAS
https://spec.openapis.org/oas/latest.html#fixed-fields-6 

it should be managed as any $ref

**Comment by daveshanley** [comment]
oh dear, this error comes from here: https://github.com/OAI/OpenAPI-Specification/blob/main/schemas/v3.1/schema.json, its not something I can control, this rule is parsing the schema and validating it. I think the schema needs updating to allow it.

**Comment by daveshanley** [comment]
Looking deeper into this: Here is when the schema validator pulls out when validating against the latest 3.1 schema: 

![Screenshot 2024-01-19 at 12 42 43 PM](https://github.com/daveshanley/vacuum/assets/187345/c94467eb-ee38-4e7e-921b-2ebc6bfacd66)

It's pointing here: https://github.com/OAI/OpenAPI-Specification/blob/main/schemas/v3.1/schema.yaml#L211

**Comment by LasneF** [comment]
good raising the topic to the OAS community

**Comment by daveshanley** [comment]
The latest OpenAPI 3.1 schema has been added into `libopenapi` and absorbed by `vacuum` in `v0.8.7` and this issue is now resolved.
