### ISSUE TITLE
integer & number minimum (& maximum) don't allow a minimum of zero (or any negative numbers)

### ISSUE THREAD

**Issue by amp001** [daveshanley/vacuum#424]
https://github.com/daveshanley/vacuum/blob/7062757738f4c4afa67cfb4a485b8dc46edb8e89/functions/openapi/schema_type.go#L86

I believe this is tripping up both integer and number schemas with a `minimum: 0` qualifier. But, integers and numbers are both signed, so why restrict the minimum (and maximum, checked a few lines below this one) to being greater than 0? You should be able to have a `minimum: -100` and a `maximum: -50` if you want to.

**Comment by daveshanley** [comment]
will provide a patch to fix this today.

**Comment by daveshanley** [comment]
This is fixed in `v0.8.1`

**Comment by darrenspurgeon** [comment]
Hi, @daveshanley . The 0.8.1 fix works now a `minimum: 0` by itself, yet I think (as @amp001 suggested) that the spec should allow for negative signed integers as well. The error is thrown for cases of `minimum: -100` and `maximum: -50`. My spec has just such a use case where min and max are both negative.

Maybe one way to validate this is to take one or all of `minimum`, `maximum`, `type`, and `format` together. For example, make sure `minimum` < value < `maximum` alongside a signed (`type: integer` + `format: int32`). Not sure.

I hope I'm not off base on this. Thanks as always!

**Comment by amp001** [comment]
Agreed @darrenspurgeon – minimum and maximum should both be numbers, and minimum should be less than maximum. Other than than, I _suppose_ if the type is integer, they should both be integers, and if the format is int32, they should be within the range of -2,147,483,648 to 2,147,437 (-2^31 to 2^31 - 1) – similarly limited for int64. In Go, the constants for these should be available as `math.MinInt32`, `math.MaxInt32`, `math.MinInt64`, and `math.MaxInt64`. 

But, other than that, I don't think I'd be overly strict on this aspect of schema definition.

**Comment by daveshanley** [comment]
Hi, I re-checked the spec, negative numbers are allowed for min/max. I will update the rule.

**Comment by daveshanley** [comment]
resolved in `v0.8.3`
