### ISSUE TITLE
`owasp-protection-global-unsafe` rule is failing to detect previously recognised cases

### ISSUE THREAD

**Issue by TheTeaCat** [daveshanley/vacuum#431]
I'm not sure what's going on here but in the example appspec, where security has been removed from the `DELETE /pets/{petId}` endpoint, the `owasp-protection-global-unsafe` doesn't pick it up any more:

```yaml
openapi: 3.0.1
info:
  title: Security disabled for specific endpoint
  version: "0.1"
servers:
  - url: https://example.com
paths:
  /pets:
    post:
      summary: "create a pet"
      responses:
        "200":
          description: some descriptive text
  /pets/{petId}:
    parameters:
      - name: petId
        in: path
        required: true
        schema:
          type: integer
    get:
      summary: "get a pet"
      responses:
        "200":
          description: some descriptive text
    delete:
      summary: "delete a pet"
      responses:
        "200":
          description: some descriptive text
      security: []
components:
  securitySchemes:
    jwt:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
  - jwt: []
```

Relevant part of [the OpenAPI spec](https://swagger.io/specification/), under the Operation Object see the description for the `security` field:

> To remove a top-level security declaration, an empty array can be used.

This was detected in earlier versions of vacuum.

I'm guessing there's something funky in the logic here:

https://github.com/daveshanley/vacuum/blob/0e30ba4eacac7b5694e3c65cc23f79a5a5394b7a/functions/owasp/check_security.go#L104-L105

When I've played around with it it starts erroneously reporting that security is also missing from the `POST /pets` endpoint too though.

**Comment by TheTeaCat** [comment]
I think it boils down to the zero value of `opValue.Security` being `[]` in both the cases where no security property is present and when a `security: []` is present.

https://github.com/pb33f/doctor/blob/3644e80c85901727e8082eea4aa5e4dac2acf25b/model/high/v3/operation.go#L20C15-L20C44

**Comment by TheTeaCat** [comment]
Bingo, if `security` is `[]` then [the `for` loop here](https://github.com/pb33f/doctor/blob/3644e80c85901727e8082eea4aa5e4dac2acf25b/model/high/v3/operation.go#L83-L93) iterates zero times, so `o.Security` is never assigned to and remains `nil`:

```golang
        if operation.Security != nil {
                for i, security := range operation.Security {
                        security := security
                        s := &drBase.SecurityRequirement{}
                        s.Parent = o
                        s.IsIndexed = true
                        s.Index = i
                        wg.Go(func() { s.Walk(ctx, security) })
                        o.Security = append(o.Security, s)
                }
        }
```

Quick fix:

```golang
        if operation.Security != nil {
		o.Security = []*drBase.SecurityRequirement{}
                for i, security := range operation.Security {
                        security := security
                        s := &drBase.SecurityRequirement{}
                        s.Parent = o
                        s.IsIndexed = true
                        s.Index = i
                        wg.Go(func() { s.Walk(ctx, security) })
                        o.Security = append(o.Security, s)
                }
        }
```

**Comment by daveshanley** [comment]
Would you mind submitting a PR? I would be most grateful.

**Comment by daveshanley** [comment]
I re-wrote all those rules pretty quickly, I am sure there are a few other gaps.

**Comment by TheTeaCat** [comment]
No worries, I'm on a lil holibob until Monday so it'll be a few days.

Otherwise if anyone else wants some easy pickings in the meantime feel
free, I'd appreciate it!

**Comment by TheTeaCat** [comment]
@daveshanley see PRs above
