### ISSUE TITLE
`path-param` rule not finding missing parameters

### ISSUE THREAD

**Issue by mehdi-sol** [daveshanley/vacuum#435]
Hey!
In this sample, the path has two params, but the `parameters` property only defines one:
<details>

```yaml
openapi: 3.0.3
info:
  description: Pizza
  title: Pizza API
  version: 1.0.0
paths:
  /pizza/{type}/{topping}:
    parameters:
      - name: type
        description: Pizza type.
        in: path
        required: true
        schema:
          type: string
    get:
      operationId: get_pizza
      summary: summary
      description: description
      responses:
        '204':
          description: no description
```

</details>

I believe this is the second bad example from [here](https://quobix.com/vacuum/rules/operations/path-params/), so it should be an error. Running vacuum v0.8.4 with the recommended ruleset on this file results in no errors. However, running spectral v6.6.0 with `spectral:oas` does pick this up.

I believe `ensureAllExpectedParamsInPathAreDefined` needs a bit of work to correctly pick this up. I'm happy to do a PR for this.

**Comment by daveshanley** [comment]
All PRs are welcome!

**Comment by mehdi-sol** [comment]
Thanks for the swift response @daveshanley. I've opened PR #436 for this issue.
