### ISSUE TITLE
Regression detecting duplicate parameters

### ISSUE THREAD

**Issue by TristanSpeakEasy** [daveshanley/vacuum#440]
A spec with duplicate parameters used to return an error from GetOperationParametersIndexErrors like:  "the get operation parameter at path /test, index 1 has a duplicate name action and in type"

but this no longer returns anything for a spec with parameters like so:

```yaml
openapi: 3.0.0
servers:
  - url: http://localhost:8080
paths:
  /test:
    get:
      parameters:
        - name: action
          in: query
          schema:
            type: string
        - name: action
          in: query
          schema:
            type: string
```

**Comment by daveshanley** [comment]
Running this exact spec through vacuum  `v0.8.7` produces this result:

<img width="1691" alt="Screenshot 2024-02-03 at 1 50 18 PM" src="https://github.com/daveshanley/vacuum/assets/187345/06e66309-03cf-4e0e-b567-5747ec2342c1">

The rules are working as expected in `v0.8.7`
