### ISSUE TITLE
$ref in path not correctly handled in case of path parameter 

### ISSUE THREAD

**Issue by LasneF** [daveshanley/vacuum#446]
since 0.8.7  and  path now support $ref 

but this looks not fully handled in correctly when there is a path parameter 

exemple : 

File  :  openapi.yaml   contains 

    /pets/{petId}:
        $ref: ./paths/pet.yaml

File : pet.yaml 

    parameters:
      - $ref: "../parameters/petId.yaml"
    
    get:
         responses:
               "200":

vacuum mentionned 

GET must define parameter petId as expected by path /pets/{petId}

**Comment by LasneF** [comment]
may be a duplicate of https://github.com/daveshanley/vacuum/issues/390

**Comment by daveshanley** [comment]
Addressed in `v0.9.0` it was fixed in libopenapi

https://github.com/pb33f/libopenapi/blob/main/index/spec_index_test.go#L1618
