### ISSUE TITLE
Description warning not accurate as parsing payload

### ISSUE THREAD

**Issue by LasneF** [daveshanley/vacuum#447]
given an object having description as field , looks it is spot as part of the linting fields wheras only API should be lintered 

![image](https://github.com/daveshanley/vacuum/assets/12461661/947d8f1e-7721-4332-8855-bdbef5f9f6cb)

**Comment by daveshanley** [comment]
Yes, this rule should not lint inside examples.

**Comment by daveshanley** [comment]
This was auto closed, but this has been fixed in `v0.9.15`. Any example / examples that contain a description are not extracted by the index anymore. 

https://github.com/pb33f/libopenapi/blob/main/index/extract_refs.go#L447
