### ISSUE TITLE
Add RateLimit to list of acceptable rate limiting headers

### ISSUE THREAD

**Issue by darrenspurgeon** [daveshanley/vacuum#458]
Enhancement request

In looking at the rule [owasp-rate-limit](https://quobix.com/vacuum/rules/owasp/owasp-rate-limit/) and comparing against the [RateLimit IETF draft](https://www.ietf.org/archive/id/draft-ietf-httpapi-ratelimit-headers-07.html), I wonder if we could add one more header string to the list of acceptable header names.

In the function `GetOWASPRateLimitRule()` (vacuum/rulesets/owasp_ruleset_functions.go), the following acceptable string values for RateLimit headers are defined:

- xRatelimitLimit = "X-RateLimit-Limit"
- xRateLimitLimit = "X-Rate-Limit-Limit"
- ratelimitLimit  = "RateLimit-Limit||RateLimit-Reset"

Those are certainly common, and in the draft the authors refer to the combined header `RateLimit` as a dictionary and examples show a combined header for limit, remaining, and reset tokens. In reviewing some of that team's Github PRs and commentary, they refer to `RateLimit` and its dictionary as the new style being proposed. For example:

```
HTTP/1.1 200 Ok
Content-Type: application/json
RateLimit: limit=100, remaining=0, reset=50
```

Can we add this to the list of acceptable values? It would be an additional var entry like: `ratelimit = "RateLimit"` and then adding it to the FunctionOptions below in the model rule.

**Comment by daveshanley** [comment]
Yes, we can add it. Please fee free to submit a PR!

**Comment by daveshanley** [comment]
This was added  in `v0.9.9`

https://github.com/daveshanley/vacuum/blob/main/rulesets/owasp_ruleset_functions.go#L277
