### ISSUE TITLE
Where is the documentation source located?

### ISSUE THREAD

**Issue by tploss** [daveshanley/vacuum#471]
I wanted to contribute a fix to the documentation but was not able to find the sources of the documentation located at https://quobix.com/vacuum
I'm sorry if I missed or overlooked it, please let me know whether it is possible to contribute to the docs directly.

**Comment by daveshanley** [comment]
Hi, unfortunately the docs source are not public as they are a part of my personal website. They were originally, but I've been building non-free / OSS content that is mixed in with it.

I can update them for you however?

**Comment by tploss** [comment]
Thanks for explaining. I had just seen a typo somewhere while reading up on some of the docs.
And then I wondered if I had really overlooked the doc sources. But now tbh I don't even remember the typo so all good 😅 

Thanks for creating great tools like vacuum!

**Comment by LasneF** [comment]
@daveshanley  you should leverage https://cspell.org/ as CLI as part of your publishing pipeline , it works as a charm
