### ISSUE TITLE
MINGW64_NT-10.0-22631 os type is not supported

### ISSUE THREAD

**Issue by kalathil-ajay-menon** [daveshanley/vacuum#491]
Unable to run vaccum on git bash

$ curl -fsSLk https://quobix.com/scripts/install_vacuum.sh | sh
Error: MINGW64_NT-10.0-22631 os type is not supported
Please create an issue so we can add support. https://github.com/daveshanley/vacuum/issues/new

**Comment by daveshanley** [comment]
I have no idea how to add support for this OS, I have never even heard of it?

**Comment by daveshanley** [comment]
No idea what to do here.
