### ISSUE TITLE
Escaping `*` in pattern is flagged as invalid `ECMA-262` regex

### ISSUE THREAD

**Issue by maboehm** [daveshanley/vacuum#496]
We have a regular expression that matches a literal `*` character (it matches a cron schedule), but this is not accepted as a ECMA-262 expression:

```json
{
  "openapi": "3.0.1",
  "info": {
    "title": "pattern-bug",
    "version": "1.0",
    "description": "example"
  },
  "paths": {},
  "components": {
    "schemas": {
      "foo": {
        "pattern": "\\*",
        "type": "string"
      }
    }
  }
}
```

```
$ vacuum lint -e -d test.json
test.json:12:9 | error    | schema `pattern` should be a ECMA-262 regular expression dialect | oas-schema-check | Schemas  | $.components.schemas['foo'].pattern
```

Interestingly, if I change the pattern to `"^\\*"` it is accepted, but e.g. `"^A(\\*)"` is not.

Done using `version: 0.9.16`

**Comment by daveshanley** [comment]
`*` is not a valid ECMA-262 expression. `\\*` is however. The way this works is that the rule literally compiles your expression to JavaScript and executes it in a VM inside the application. 

See the code here: 

https://github.com/daveshanley/vacuum/blob/main/functions/openapi/schema_type.go#L143

If the `RegExp('YOUR PATTERN")` fails to compile, then the violation is triggered. 

To validate, try and use `*` as a ECMA regex on https://regex101.com/

![Screenshot 2024-05-25 at 9 41 22 AM](https://github.com/daveshanley/vacuum/assets/187345/e2fddb6a-7007-4a5f-8175-97cbc8a79634)

![Screenshot 2024-05-25 at 9 42 15 AM](https://github.com/daveshanley/vacuum/assets/187345/0be4ebf6-6d9e-42e7-b4c7-cffd0715278f)
