### ISSUE TITLE
Nil pointer dereference issue on OWASP JWT rule

### ISSUE THREAD

**Issue by bravenut** [daveshanley/vacuum#497]
Hi Dave,

I noticed some edge case today where the "jwt_best_practice" OWASP rule leads to a nil pointer dereference issue when trying to dereference the `StartNode` of a `*model.RuleFunctionResult`.

I think the issue lies here (it assumes that there is a description on each item within the securityScheme components):
https://github.com/daveshanley/vacuum/blob/99df10d7e2f8dd811c2f00f765ec6ef5568164fd/functions/owasp/jwt_best_practice.go#L38

**To reproduce:**
Put a security scheme of bearerFormat jwt without a description:
```
openapi: "3.1.0"
info:
  version: "1.0"
components:
  securitySchemes:
    "bad bearer jwt":
      type: "http"
      bearerFormat: "jwt"
```

I think, if there is no description, the parent (security scheme "key") could be used as key node. If I find some time, I will suggest the corresponding changes.

Edit: My suggestion, between l. 38-39 (in [jwt_best_practice.go](https://github.com/daveshanley/vacuum/blob/99df10d7e2f8dd811c2f00f765ec6ef5568164fd/functions/owasp/jwt_best_practice.go#L37C5-L49C6)):

```
if node == nil {
    node = scheme.Value.GoLow().KeyNode
}
```

**Comment by daveshanley** [comment]
Fixed in `v0.10.0` Thank you.
