### ISSUE TITLE
Path is truncated in output

### ISSUE THREAD

**Issue by LasneF** [daveshanley/vacuum#506]
given an api specification 

doing vacuum

vacuum lint .\component-descriptor.yml -d 

return a nice array , but the line is limited to 200 chars 
but it gives only 65 char for the path that is a bit short 

we may need a mode to display not as a table but with 2 lines 

not sure 

notice , this ticket can be closed with no further notice , i am not waiting too munch on it , the most important is that it give the right line and it gives it !

**Comment by lobocv** [comment]
Agreed. There's no way to show the full results. The fix is quite easy but i'm not sure if it would mess up the table view?

**Comment by daveshanley** [comment]
The new `--no-clip` flag for the `lint` command in `v0.12.0` has resolved this issue.
