### ISSUE TITLE
Linter as a package and configure vacuum.conf.yaml

### ISSUE THREAD

**Issue by Gouveia15** [daveshanley/vacuum#534]
Hello guys!
I have a question and I'm looking for someone that has tied this before to see if I can get some help.
I basically have a repo that consists of YAML rules to be used with vacuum, I want for other people to use my linter so I turned into a npm package to be used for example in CI/CD pipelines.
My question is, how can I use the conf file the same way I used in spectral? Meaning, people usudally install my package and vacuum, then the only thing I want them for them to do is like what I used to have in spectral: 
echo 'extends: ["@api-program/api-linter"]' > .spectral.yaml (in this case I want it to be vacuum.conf.yaml) I've tried it but doesn't work, this command is supposed to be in a CICD pipleine.
And the main file that I want this new conf file to point is mine called "all-ruleset.yaml" which is bascially a yaml that extends all my seperated rulesets: 

```
extends:
  - "src/rulesets/contract-information-ruleset.yaml"
  - "src/rulesets/descriptions-ruleset.yaml"
  - "src/rulesets/examples-ruleset.yaml"
  - "src/rulesets/operations-path-ruleset.yaml"
  - "src/rulesets/owasp-ruleset.yaml"
  - "src/rulesets/schemas-ruleset.yaml"
  - "src/rulesets/security-ruleset.yaml"
  - "src/rulesets/tags-ruleset.yaml"
  - "src/rulesets/validation-ruleset.yaml"
  - "src/rulesets/custom-functions-ruleset.yaml"
```

this works nice when I point to the file, but I'm not able to use the conf file outside of the linter project nor a CI/CD pipleine, any ideas?

**Comment by daveshanley** [comment]
https://quobix.com/vacuum/rulesets/sharing/ All the docs you need for including, embedding, sharing rulesets.

**Comment by daveshanley** [comment]
Let me know if you need any more help than the docs above.
