### ISSUE TITLE
Error on `example` when `exclusiveMinimum` is used with OAS 3.0.X

### ISSUE THREAD

**Issue by busches** [daveshanley/vacuum#564]
I'm getting a linter error about my example being invalid, but the error is: `jsonschema file:///work/schema.json compilation failed: '/properties/fieldWithExclusiveMinimum/exclusiveMinimum' does not validate with https://json-schema.org/draft/2020-12/schema#/allOf/1/$ref/properties/properties/additionalProperties/$dynamicRef/allOf/3/$ref/properties/exclusiveMinimum/type: expected number, but got boolean`

OAS 3.0 has `exclusiveMinimum` as type boolean, OAS 3.1 swaps it to a number. Of course if I try and change it to a number, then I get an error, instead of an error on my example.

Screenshot of the `html-report`
![image](https://github.com/user-attachments/assets/5a3a3ed2-2d84-4799-a347-4e83d3b9fcf6)

Sample spec to recreate, it has two warnings, both only on the examples.

```yaml
openapi: 3.0.3
info:
  title: Test Bug
  description: |
    jsonschema file:///work/schema.json compilation failed: '/exclusiveMinimum' does not validate with https://json-schema.org/draft/2020-12/schema#/allOf/3/$ref/properties/exclusiveMinimum/type: expected number, but got boolean
  version: 3.4.7
servers:
- url: localhost
tags:
  - name: moo
paths:
  /test-bug:
    post:
      tags:
        - moo
      summary: Recreate the bug
      description: recreate the bug
      operationId: post-bug
      requestBody:
        description: body of request
        content:
          application/json:
            schema:
              type: object
              properties:
                fieldWithExclusiveMinimum:
                  minimum: 0
                  exclusiveMinimum: true
                  type: number
                  description: OAS 3.0 has exclusiveMinimum as a boolean, yet the linter warns saying my example is bad as it's not a boolean
                  example: 1.0001
            example:
              fieldWithExclusiveMinimum: 0.1
        required: true
      responses:
        "201":
          description: Success
```

All version of `openapi` from `3.0.0` to `3.0.3` have the same issue, the issue does not occur in `3.1.0` ironically, as `exclusiveMinimum: boolean` should throw the exact error above.

Appreciate the help, as we're not able to upgrade to OAS 3.1 yet for this specification.

**Comment by daveshanley** [comment]
not sure what is going on here, will look into it.

**Comment by daveshanley** [comment]
Which version of vacuum are you using?

**Comment by daveshanley** [comment]
I cannot re-create this with the latest version. I can re-create it with anything below `v0.13.2`

**Comment by daveshanley** [comment]
Here is a screenshot of the openapi doctor running vacuum `v0.13.1` You can see the error. 
(https://pb33f.io/doctor/)

![Screenshot 2024-10-03 at 8 51 36 AM](https://github.com/user-attachments/assets/a9a64991-09b0-423c-a188-44ed19d6eea8)

Here is my local version of the doctor, which is unreleased (but using the latest version of vacuum). 

![Screenshot 2024-10-03 at 8 51 48 AM](https://github.com/user-attachments/assets/a02f634a-5e44-4caa-b88b-70de6b890541)

No error on the example.

**Comment by busches** [comment]
I'm using the docker image:
```
docker run  dshanley/vacuum version
latest
```

Not super helpful :D

Here's what `docker inspect` had:

```
 "Id": "sha256:43b0e9fa380fb376d7eb3045d8f34915d3f8895eabe84265ddd1c3e8480699ae",
        "RepoTags": [
            "dshanley/vacuum:latest"
        ],
        "RepoDigests": [
            "dshanley/vacuum@sha256:1f50fdc8bdaabae870caf8de56e75bf6d310b7a199e8d750e701ac2b263b52f3"
        ],
        "Parent": "",
        "Comment": "buildkit.dockerfile.v0",
        "Created": "2024-09-10T01:34:22.249150731Z",
```

**Comment by busches** [comment]
I repulled the latest version from docker and the error is gone now, awesome! I did have an html-report, but it doesn't say what version it was. Thanks!
