### ISSUE TITLE
Cant't lint in real-time

### ISSUE THREAD

**Issue by xcccdjsn** [daveshanley/vacuum#571]
It does not work after first linting that the relevant messages has not been updated.

I use it in neovim with reference configuration of plugin nvim-lspconfig.

**Comment by daveshanley** [comment]
I don't know how to help here, I don't use neovim, other users who do don't seem to have this issue. Same with VSCode or any other editor using the language server.

**Comment by jettandres** [comment]
neovim user here! I managed to make it work via nvim-lspconfig. See [here](https://github.com/neovim/nvim-lspconfig/blob/master/doc/configs.md#vacuum)

Also worth mentioning the default filename for it automatically start is `openapi.*.yaml` make sure to extend the filetypes as mentioned if you use a different format

**Comment by daveshanley** [comment]
This is a really good link to seek help on this topic. I can't help any further, so folks that run into this issue, there are  vacuum docs built into the neovim docs. 

https://github.com/neovim/nvim-lspconfig/blob/master/doc/configs.md#vacuum
