### ISSUE TITLE
BUG : OAS 3.1.1 not supported ( detected as OAS 3.0 and fail pattern matching) 

### ISSUE THREAD

**Issue by LasneF** [daveshanley/vacuum#579]
given the  unit test func TestOAS3Schema_RunRule_Pass(t *testing.T)  

when changing the openapi version from 3.0.0 to 3.1.0 it works , but changing it to 3.1.1 it fails with the fallowing error message 

  Error:          "[{schema invalid: '3.1.1' does not match pattern '^3\\.0\\.\\d(-.+)?$' {{0 0} {0 0}} 
  
  suprisingly it pickup the wrong regular expression 'ie the 3.0.X , this issue is so affecting the Doctor

**Comment by LasneF** [comment]
will create a PR the issue comes from libOpenAPI there 
https://github.com/pb33f/libopenapi/blob/main/datamodel/spec_info.go#L118

**Comment by daveshanley** [comment]
Fixed in `v0.14.3`, updated to the latest `libopenapi`
